-- Auto-generated by theme/generate.sh — do not edit manually
-- Generated: 2026-08-15 18:00:21
local with_alpha = function(color, alpha)
  if alpha > 1.0 or alpha < 0.0 then return color end
  return (color & 0x00ffffff) | (math.floor(alpha * 255.0) << 24)
end

return {
  black      = 0xff181a1b,
  white      = 0xffd2dbe0,
  red        = 0xff874b38,
  green      = 0xff425e67,
  blue       = 0xff2d7099,
  yellow     = 0xffeca081,
  orange     = 0xffc87b62,
  magenta    = 0xff745c66,
  grey       = 0xff6d7174,
  transparent = 0x00000000,

  bar = {
    bg     = 0x00181a1b,
    border = 0xff4c3d43,
  },
  popup = {
    bg     = 0xc0493d3d,
    border = 0xff6d7174,
  },
  bg1 = 0xff493d3d,
  bg2 = 0xff4c3d43,

  -- Per-display accent/bg tones (from each monitor's wallpaper)
  display = {
    [1] = { accent = 0xffe39075, bg1 = 0xff493d3d, bg2 = 0xff4c3d43 },
    [2] = { accent = 0xffe39075, bg1 = 0xff493d3d, bg2 = 0xff4c3d43 },
    [3] = { accent = 0xffe39075, bg1 = 0xff493d3d, bg2 = 0xff4c3d43 },
  },

  with_alpha = with_alpha,
}
