-- Auto-generated by theme/generate.sh — do not edit manually
-- Generated: 2026-06-08 18:08:25
local with_alpha = function(color, alpha)
  if alpha > 1.0 or alpha < 0.0 then return color end
  return (color & 0x00ffffff) | (math.floor(alpha * 255.0) << 24)
end

return {
  black      = 0xff030303,
  white      = 0xffe1e1e1,
  red        = 0xffd60000,
  green      = 0xff00d600,
  blue       = 0xff0047d6,
  yellow     = 0xffd6c400,
  orange     = 0xffd65900,
  magenta    = 0xffc400d6,
  grey       = 0xff757575,
  transparent = 0x00000000,

  bar = {
    bg     = 0x00030303,
    border = 0xff454545,
  },
  popup = {
    bg     = 0xc0454545,
    border = 0xff757575,
  },
  bg1 = 0xff454545,
  bg2 = 0xff454545,

  -- Per-display accent/bg tones (from each monitor's wallpaper)
  display = {
    [1] = { accent = 0xffd60000, bg1 = 0xff454545, bg2 = 0xff454545 },
    [2] = { accent = 0xffd60000, bg1 = 0xff454545, bg2 = 0xff454545 },
    [3] = { accent = 0xffd60000, bg1 = 0xff454545, bg2 = 0xff454545 },
  },

  with_alpha = with_alpha,
}
