#!/usr/bin/env python3
"""Push the wallpaper palette into ghostty, atuin, yazi, and eza configs.

Reads the same SKETCHYBAR_COLOR_* env vars that colors_generated.sh exports
for shell rc / tmux.conf — generate.sh sources that file before invoking
this script, so there's a single source of truth for the palette.

- ghostty: writes ghostty/colors_generated.conf (included via config-file)
- atuin:   writes atuin/themes/sketchybar.toml (a full theme file)
- yazi:    patches a handful of chrome keys in yazi/theme.toml in place
- eza:     patches a handful of accent keys in eza/theme.yml in place
- nvim:    writes nvim/lua/colors_generated.lua (a full tokyonight-shaped
           palette), consumed by nvim/colors/wallpaper.lua

Only touches ~fixed keys, not the tools' full themes — everything else
in yazi/theme.toml and eza/theme.yml stays hand-authored.
"""

import os
import re
import sys
import colorsys
import datetime


# ── Color math (mirrors tokyonight.nvim's util.lua blend/brighten) ─────────────

def _hex_to_rgb(hexstr):
    h = hexstr.lstrip("#")
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


def _rgb_to_hex(r, g, b):
    r, g, b = (max(0, min(255, round(v))) for v in (r, g, b))
    return f"#{r:02x}{g:02x}{b:02x}"


def blend(hex1, hex2, ratio):
    """ratio=0 -> hex1, ratio=1 -> hex2 (linear RGB mix)."""
    r1, g1, b1 = _hex_to_rgb(hex1)
    r2, g2, b2 = _hex_to_rgb(hex2)
    return _rgb_to_hex(
        r1 + (r2 - r1) * ratio,
        g1 + (g2 - g1) * ratio,
        b1 + (b2 - b1) * ratio,
    )


def lighten(hexstr, amount):
    r, g, b = _hex_to_rgb(hexstr)
    h, s, v = colorsys.rgb_to_hsv(r / 255, g / 255, b / 255)
    v = min(1.0, v + amount)
    r, g, b = colorsys.hsv_to_rgb(h, s, v)
    return _rgb_to_hex(r * 255, g * 255, b * 255)


def darken(hexstr, amount):
    r, g, b = _hex_to_rgb(hexstr)
    h, s, v = colorsys.rgb_to_hsv(r / 255, g / 255, b / 255)
    v = max(0.0, v - amount)
    r, g, b = colorsys.hsv_to_rgb(h, s, v)
    return _rgb_to_hex(r * 255, g * 255, b * 255)


def brighten(hexstr):
    return lighten(hexstr, 0.15)


def load_colors():
    keys = ("black", "white", "red", "green", "blue", "yellow",
            "orange", "magenta", "grey", "bg1", "bg2", "bar_bg", "accent")
    colors = {}
    for k in keys:
        v = os.environ.get(f"SKETCHYBAR_COLOR_{k.upper()}")
        if not v:
            print(f"Missing SKETCHYBAR_COLOR_{k.upper()} in environment", file=sys.stderr)
            sys.exit(1)
        colors[k] = v
    return colors


def write_ghostty(colors, config_root):
    out = os.path.join(config_root, "ghostty", "colors_generated.conf")
    ts = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines = [
        "# Auto-generated by sketchybar/theme/generate.sh — do not edit manually",
        f"# Generated: {ts}",
        f"selection-background = {colors['bg2'][1:]}",
        f"selection-foreground = {colors['white'][1:]}",
        f"split-divider-color = {colors['grey'][1:]}",
        f"unfocused-split-fill = {colors['bar_bg'][1:]}",
    ]
    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Generated: {out}")


def write_atuin(colors, config_root):
    out = os.path.join(config_root, "atuin", "themes", "sketchybar.toml")
    ts = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines = [
        "# Auto-generated by sketchybar/theme/generate.sh — do not edit manually",
        f"# Generated: {ts}",
        "",
        "[theme]",
        'name = "sketchybar"',
        "",
        "[colors]",
        f'Base = "{colors["white"]}"',
        f'Title = "{colors["accent"]}"',
        f'Muted = "{colors["grey"]}"',
        f'Annotation = "{colors["grey"]}"',
        f'Guidance = "{colors["blue"]}"',
        f'Important = "{colors["magenta"]}"',
        f'AlertInfo = "{colors["green"]}"',
        f'AlertWarn = "{colors["yellow"]}"',
        f'AlertError = "{colors["red"]}"',
    ]
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Generated: {out}")


def replace_in_section(text, section, key, new_value):
    """Replace `key = ...` with `key = new_value`, scoped to one [section]."""
    sec_match = re.search(rf'^\[{re.escape(section)}\]$', text, re.MULTILINE)
    if not sec_match:
        return text
    start = sec_match.end()
    next_header = re.search(r'^\[', text[start:], re.MULTILINE)
    end = start + next_header.start() if next_header else len(text)
    block = text[start:end]
    block, n = re.subn(
        rf'^{re.escape(key)} = .*$', f'{key} = {new_value}', block,
        count=1, flags=re.MULTILINE,
    )
    if n == 0:
        return text
    return text[:start] + block + text[end:]


def patch_yazi(colors, config_root):
    path = os.path.join(config_root, "yazi", "theme.toml")
    with open(path) as f:
        text = f.read()

    accent, red, grey = colors["accent"], colors["red"], colors["grey"]
    white, black, green, yellow = colors["white"], colors["black"], colors["green"], colors["yellow"]

    patches = [
        ("mgr", "cwd", f'{{ fg = "{accent}" }}'),
        ("mgr", "count_copied", f'{{ fg = "{white}", bg = "{green}" }}'),
        ("mgr", "count_cut", f'{{ fg = "{white}", bg = "{red}" }}'),
        ("mgr", "count_selected", f'{{ fg = "{black}", bg = "{yellow}" }}'),
        ("mgr", "border_style", f'{{ fg = "{grey}" }}'),
        ("tabs", "active", f'{{ bg = "{accent}", bold = true }}'),
        ("tabs", "inactive", f'{{ fg = "{accent}", bg = "{grey}" }}'),
        ("mode", "normal_main", f'{{ bg = "{accent}", bold = true }}'),
        ("mode", "normal_alt", f'{{ fg = "{accent}", bg = "{grey}" }}'),
        ("mode", "select_main", f'{{ bg = "{red}", bold = true }}'),
        ("mode", "select_alt", f'{{ fg = "{red}", bg = "{grey}" }}'),
        ("mode", "unset_main", f'{{ bg = "{red}", bold = true }}'),
        ("mode", "unset_alt", f'{{ fg = "{red}", bg = "{grey}" }}'),
    ]
    for section, key, value in patches:
        text = replace_in_section(text, section, key, value)

    with open(path, "w") as f:
        f.write(text)
    print(f"Patched: {path}")


def replace_yaml_key(text, key, new_hex, section=None):
    """Replace `key: { foreground: "..." }` with new_hex.

    If section is given, scope to the `section:` block (2-space-indented
    children, up to the next zero-indent key or EOF) — needed because some
    key names (e.g. "normal") appear under more than one section with
    different intended colors. If section is None, match a zero-indent
    top-level key instead.
    """
    if section is None:
        text, _ = re.subn(
            rf'^({re.escape(key)}: {{ foreground: )"[^"]*"( }})$',
            rf'\g<1>"{new_hex}"\g<2>',
            text, count=1, flags=re.MULTILINE,
        )
        return text

    sec_match = re.search(rf'^{re.escape(section)}:$', text, re.MULTILINE)
    if not sec_match:
        return text
    start = sec_match.end()
    next_top = re.search(r'^\S', text[start:], re.MULTILINE)
    end = start + next_top.start() if next_top else len(text)
    block = text[start:end]
    block, n = re.subn(
        rf'^(  {re.escape(key)}: {{ foreground: )"[^"]*"( }})$',
        rf'\g<1>"{new_hex}"\g<2>',
        block, count=1, flags=re.MULTILINE,
    )
    if n == 0:
        return text
    return text[:start] + block + text[end:]


def patch_eza(colors, config_root):
    path = os.path.join(config_root, "eza", "theme.yml")
    with open(path) as f:
        text = f.read()

    white, black, red, green = colors["white"], colors["black"], colors["red"], colors["green"]
    blue, yellow, orange = colors["blue"], colors["yellow"], colors["orange"]
    magenta, grey, bg2, accent = colors["magenta"], colors["grey"], colors["bg2"], colors["accent"]

    # (section, key, value) — only structural/chrome roles. file_type:,
    # filenames:, and extensions: are left untouched: those are per-item
    # identity colors (many distinct hand-picked hues for scanability),
    # not theme chrome, and collapsing them into 9 colors would just make
    # everything look the same.
    patches = [
        ("filekinds", "normal", white),
        ("filekinds", "directory", accent),
        ("filekinds", "symlink", blue),
        ("filekinds", "pipe", bg2),
        ("filekinds", "block_device", yellow),
        ("filekinds", "char_device", yellow),
        ("filekinds", "socket", bg2),
        ("filekinds", "special", magenta),
        ("filekinds", "executable", green),
        ("filekinds", "mount_point", blue),

        ("perms", "user_read", blue),
        ("perms", "user_write", magenta),
        ("perms", "user_execute_file", green),
        ("perms", "user_execute_other", green),
        ("perms", "group_read", blue),
        ("perms", "group_write", orange),
        ("perms", "group_execute", green),
        ("perms", "other_read", blue),
        ("perms", "other_write", red),
        ("perms", "other_execute", green),
        ("perms", "special_user_file", red),
        ("perms", "special_other", red),
        ("perms", "attribute", grey),

        ("size", "major", blue),
        ("size", "minor", magenta),
        ("size", "number_byte", grey),
        ("size", "number_kilo", blue),
        ("size", "number_mega", blue),
        ("size", "number_giga", orange),
        ("size", "number_huge", red),
        ("size", "unit_byte", grey),
        ("size", "unit_kilo", blue),
        ("size", "unit_mega", blue),
        ("size", "unit_giga", orange),
        ("size", "unit_huge", red),

        ("users", "user_you", blue),
        ("users", "user_root", magenta),
        ("users", "user_other", blue),
        ("users", "group_yours", blue),
        ("users", "group_root", magenta),
        ("users", "group_other", white),

        ("links", "normal", blue),
        ("links", "multi_link_file", blue),

        ("git", "new", green),
        ("git", "modified", magenta),
        ("git", "deleted", red),
        ("git", "renamed", blue),
        ("git", "typechange", blue),
        ("git", "ignored", grey),
        ("git", "conflicted", orange),

        ("git_repo", "branch_main", grey),
        ("git_repo", "branch_other", blue),
        ("git_repo", "git_clean", bg2),
        ("git_repo", "git_dirty", magenta),

        (None, "punctuation", grey),
        (None, "date", yellow),
        (None, "inode", grey),
        (None, "blocks", grey),
        (None, "header", white),
        (None, "octal", orange),
        (None, "flags", magenta),
        (None, "symlink_path", blue),
        (None, "control_char", orange),
        (None, "broken_symlink", red),
        (None, "broken_path_overlay", red),
    ]
    for section, key, value in patches:
        text = replace_yaml_key(text, key, value, section)

    with open(path, "w") as f:
        f.write(text)
    print(f"Patched: {path}")


def patch_ls_colors(colors, config_root):
    """Patch EZA_COLORS / LS_COLORS in zsh/exports/paths.zsh — these
    duplicate eza's filekinds: roles as raw ANSI RGB, used by zsh's
    completion listing and anything else that reads $LS_COLORS. Per-
    extension entries inside LS_COLORS are left untouched (same reasoning
    as file_type:/extensions: in eza's theme.yml).
    """
    path = os.path.join(config_root, "zsh", "exports", "paths.zsh")
    with open(path) as f:
        text = f.read()

    role_map = {
        "di": colors["accent"],
        "ln": colors["blue"],
        "ex": colors["green"],
        "pi": colors["bg2"],
        "so": colors["bg2"],
        "bd": colors["yellow"],
        "cd": colors["yellow"],
        "or": colors["red"],
    }
    for key, hex_value in role_map.items():
        h = hex_value.lstrip("#")
        rgb = f"{int(h[0:2], 16)};{int(h[2:4], 16)};{int(h[4:6], 16)}"
        # Lookbehind requires the key to start right after a ':' or the
        # opening '"' — excludes e.g. "*.tex=" / "*.ex=" extension entries,
        # which only share the trailing "ex=" substring, not the boundary.
        text = re.sub(rf'(?<=[:"]){key}=38;2;\d+;\d+;\d+', f'{key}=38;2;{rgb}', text)

    with open(path, "w") as f:
        f.write(text)
    print(f"Patched: {path}")


def write_nvim_colors(colors, config_root):
    """Derive a tokyonight.nvim-shaped palette (same field names/structure)
    from the wallpaper colors, so nvim/colors/wallpaper.lua's hand-written
    highlight groups — and lualine.lua's `require("colors_generated")` —
    have every field tokyonight's own palette would have, without needing
    tokyonight installed or active.
    """
    out = os.path.join(config_root, "nvim", "lua", "colors_generated.lua")
    ts = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    bg = colors["black"]
    fg = colors["white"]
    grey = colors["grey"]
    red, orange, yellow = colors["red"], colors["orange"], colors["yellow"]
    green, blue, magenta = colors["green"], colors["blue"], colors["magenta"]
    accent, bg1, bg2 = colors["accent"], colors["bg1"], colors["bg2"]

    bg_dark = darken(bg, 0.03)
    bg_dark1 = darken(bg, 0.05)
    bg_highlight = bg1
    fg_dark = blend(fg, grey, 0.5)
    fg_gutter = blend(grey, bg_highlight, 0.5)
    comment = grey
    dark3 = grey
    dark5 = lighten(grey, 0.25)

    red1 = darken(red, 0.12)
    green1 = lighten(green, 0.15)
    green2 = darken(green, 0.08)
    blue0 = darken(blue, 0.22)
    blue1 = accent
    # blend toward fg (not accent): accent is near-complementary to blue on
    # this wallpaper, so blending the two averages toward a muddy grey.
    blue2 = blend(blue, fg, 0.25)
    blue5 = lighten(blue, 0.28)
    blue6 = lighten(blue, 0.42)
    blue7 = darken(blue, 0.32)
    cyan = blue  # no real cyan in the wallpaper palette
    teal = blend(green, blue, 0.5)
    magenta2 = blend(magenta, red, 0.4)
    purple = blend(magenta, blue, 0.3)

    terminal_black = bg2
    black = blend(bg, "#000000", 0.15)
    border = black
    border_highlight = blend(bg, blue1, 0.8)

    bg_popup = bg_highlight
    bg_statusline = bg_dark
    bg_visual = blend(bg, blue0, 0.4)
    bg_search = blue0
    fg_sidebar = fg_dark
    fg_float = fg

    diff_add = blend(bg, green2, 0.25)
    diff_delete = blend(bg, red1, 0.25)
    diff_change = blend(bg, blue7, 0.15)
    diff_text = blue7

    lines = [
        "-- Auto-generated by sketchybar/theme/generate.sh — do not edit manually",
        f"-- Generated: {ts}",
        "-- Shaped like tokyonight.nvim's Palette (see :h tokyonight) so",
        "-- nvim/colors/wallpaper.lua and lualine.lua can consume it directly.",
        "return {",
        f'  bg = "{bg}",',
        f'  bg_dark = "{bg_dark}",',
        f'  bg_dark1 = "{bg_dark1}",',
        f'  bg_highlight = "{bg_highlight}",',
        f'  bg_popup = "{bg_popup}",',
        f'  bg_statusline = "{bg_statusline}",',
        f'  bg_sidebar = "NONE",',
        f'  bg_float = "NONE",',
        f'  bg_visual = "{bg_visual}",',
        f'  bg_search = "{bg_search}",',
        f'  fg = "{fg}",',
        f'  fg_dark = "{fg_dark}",',
        f'  fg_gutter = "{fg_gutter}",',
        f'  fg_sidebar = "{fg_sidebar}",',
        f'  fg_float = "{fg_float}",',
        f'  comment = "{comment}",',
        f'  dark3 = "{dark3}",',
        f'  dark5 = "{dark5}",',
        f'  black = "{black}",',
        f'  border = "{border}",',
        f'  border_highlight = "{border_highlight}",',
        f'  terminal_black = "{terminal_black}",',
        f'  none = "NONE",',
        "",
        f'  red = "{red}",',
        f'  red1 = "{red1}",',
        f'  orange = "{orange}",',
        f'  yellow = "{yellow}",',
        f'  green = "{green}",',
        f'  green1 = "{green1}",',
        f'  green2 = "{green2}",',
        f'  blue = "{blue}",',
        f'  blue0 = "{blue0}",',
        f'  blue1 = "{blue1}",',
        f'  blue2 = "{blue2}",',
        f'  blue5 = "{blue5}",',
        f'  blue6 = "{blue6}",',
        f'  blue7 = "{blue7}",',
        f'  cyan = "{cyan}",',
        f'  teal = "{teal}",',
        f'  magenta = "{magenta}",',
        f'  magenta2 = "{magenta2}",',
        f'  purple = "{purple}",',
        "",
        f'  error = "{red1}",',
        f'  warning = "{yellow}",',
        f'  info = "{blue2}",',
        f'  hint = "{teal}",',
        f'  todo = "{blue}",',
        "",
        "  git = {",
        f'    add = "{green}",',
        f'    change = "{blue}",',
        f'    delete = "{red}",',
        f'    ignore = "{dark3}",',
        "  },",
        "  diff = {",
        f'    add = "{diff_add}",',
        f'    delete = "{diff_delete}",',
        f'    change = "{diff_change}",',
        f'    text = "{diff_text}",',
        "  },",
        "  rainbow = {",
        f'    "{blue}", "{yellow}", "{green}", "{teal}",',
        f'    "{magenta}", "{purple}", "{orange}", "{red}",',
        "  },",
        "  terminal = {",
        f'    black = "{black}", black_bright = "{terminal_black}",',
        f'    red = "{red}", red_bright = "{brighten(red)}",',
        f'    green = "{green}", green_bright = "{brighten(green)}",',
        f'    yellow = "{yellow}", yellow_bright = "{brighten(yellow)}",',
        f'    blue = "{blue}", blue_bright = "{brighten(blue)}",',
        f'    magenta = "{magenta}", magenta_bright = "{brighten(magenta)}",',
        f'    cyan = "{cyan}", cyan_bright = "{brighten(cyan)}",',
        f'    white = "{fg_dark}", white_bright = "{fg}",',
        "  },",
        "}",
    ]

    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Generated: {out}")


def patch_omp(colors, config_root):
    path = os.path.join(config_root, "zsh", "external", "oh-my-posh", "default.json")
    with open(path) as f:
        text = f.read()

    # path uses the accent (matches eza's directory color), username uses blue.
    patches = {
        "blue": colors["accent"],
        "cyan": colors["blue"],
        "green": colors["green"],
        "purple": colors["magenta"],
        "red": colors["red"],
        "yellow": colors["yellow"],
        "comment": colors["grey"],
    }
    for key, value in patches.items():
        text, _ = re.subn(
            rf'^(    "{re.escape(key)}": )"#[0-9a-fA-F]{{6}}"(,?)$',
            rf'\g<1>"{value}"\g<2>',
            text, count=1, flags=re.MULTILINE,
        )

    with open(path, "w") as f:
        f.write(text)
    print(f"Patched: {path}")


def main(config_root):
    colors = load_colors()
    write_ghostty(colors, config_root)
    write_atuin(colors, config_root)
    patch_yazi(colors, config_root)
    patch_eza(colors, config_root)
    patch_ls_colors(colors, config_root)
    write_nvim_colors(colors, config_root)
    patch_omp(colors, config_root)


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: generate_downstream.py config_root", file=sys.stderr)
        sys.exit(1)
    main(sys.argv[1])
