#!/usr/bin/env python3
"""Generate colors_generated.sh (shell export vars) from three per-display JSON palette files.

Mirrors generate_lua.py so other tools (shell prompt, tmux, etc.) can pick up
the same wallpaper-derived palette via env vars.
"""

import sys
import json
import datetime

TN = {
    "black": "0xff1a1b26", "white": "0xffc0caf5",
    "red": "0xfff7768e", "green": "0xff9ece6a",
    "blue": "0xff7aa2f7", "yellow": "0xffe0af68",
    "orange": "0xffff9e64", "magenta": "0xffbb9af7",
    "grey": "0xff565f89",
    "bg1": "0xff1f2335", "bg2": "0xff24283b",
    "bar_bg": "0x001a1b26", "bar_border": "0xff292e42",
    "popup_bg": "0xc01f2335", "popup_border": "0xff565f89",
    "accent": "0xff7aa2f7",
}


def load(path):
    try:
        with open(path) as f:
            d = json.load(f)
        return d or {}
    except Exception:
        return {}


def g(p, k):
    return p.get(k) or TN.get(k, "0xff000000")


def rgb(argb_hex):
    """0xAARRGGBB -> #RRGGBB"""
    return "#" + argb_hex[-6:]


def main(p1_path, p2_path, p3_path, out_path):
    palettes = [load(p) for p in [p1_path, p2_path, p3_path]]
    gp = palettes[0]

    def disp(p):
        return {k: g(p, k) for k in ("accent", "bg1", "bg2")}

    d = [disp(p) for p in palettes]
    ts = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    keys = ("black", "white", "red", "green", "blue", "yellow", "orange", "magenta", "grey",
            "bg1", "bg2", "bar_bg", "bar_border", "popup_bg", "popup_border", "accent")

    lines = [
        "# Auto-generated by theme/generate.sh — do not edit manually",
        f"# Generated: {ts}",
        "# Source this from your shell rc / tmux.conf to reuse the sketchybar wallpaper palette.",
    ]
    for k in keys:
        lines.append(f"export SKETCHYBAR_COLOR_{k.upper()}=\"{rgb(g(gp, k))}\"")

    lines.append("")
    lines.append("# Per-display accent/bg tones (from each monitor's wallpaper)")
    for i in range(3):
        n = i + 1
        lines.append(f"export SKETCHYBAR_COLOR_ACCENT_{n}=\"{rgb(d[i]['accent'])}\"")
        lines.append(f"export SKETCHYBAR_COLOR_BG1_{n}=\"{rgb(d[i]['bg1'])}\"")
        lines.append(f"export SKETCHYBAR_COLOR_BG2_{n}=\"{rgb(d[i]['bg2'])}\"")

    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Generated: {out_path}")


if __name__ == "__main__":
    if len(sys.argv) != 5:
        print("Usage: generate_env.py d1.json d2.json d3.json output.sh", file=sys.stderr)
        sys.exit(1)
    main(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4])
